name: "001-news"
services:
  frontend:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./app/frontend/:/app
    command: npm start
    networks:
      - default
    
  server:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./app/backend/:/app
    command: npm run watch
    networks:
      - default
  
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default
    ports:
      - 8888:80
networks:
  default:


